name: Build .deb packages
on:
  push:
    branches:
      - master
      - build*
    tags:
      - v*
env:
  JITSI_ARTIFACTS_FOLDER: /var/www/downloads.optidata.cloud/jitsi/artifacts
  OPTIDATA_DOWNLOADS_HOST: 209.14.141.164
jobs:
  build-push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Npm install
        run: npm install
      - name: Run Make
        run: make
      - name: Build .deb packages
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -us -uc -b
          artifacts-dir: debian/artifacts
      - name: Prepare download folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.OPTIDATA_DOWNLOADS_HOST }}
          username: ${{ secrets.OPTIDATA_DOWNLOADS_USERNAME }}
          password: ${{ secrets.OPTIDATA_DOWNLOADS_PASSWORD }}
          port: ${{ secrets.OPTIDATA_DOWNLOADS_PORT }}
          script: mkdir -p ${{ env.JITSI_ARTIFACTS_FOLDER }}
      - name: Upload .deb packages
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ env.OPTIDATA_DOWNLOADS_HOST }}
          username: ${{ secrets.OPTIDATA_DOWNLOADS_USERNAME }}
          password: ${{ secrets.OPTIDATA_DOWNLOADS_PASSWORD }}
          port: ${{ secrets.OPTIDATA_DOWNLOADS_PORT }}
          local: debian/artifacts
          remote: ${{ env.JITSI_ARTIFACTS_FOLDER }}


