name: Build Docker Images
on:
  push:
    tags:
      - docker-*
jobs:
  build-push:
    name: optiwork-jitsi:${{ matrix.details.region }}-${{ github.ref_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        details: [
          {region: br, dockerfile: ./devops/br/Dockerfile}, 
          {region: us, dockerfile: ./devops/us/Dockerfile}, 
          {region: eu, dockerfile: ./devops/eu/Dockerfile}]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.details.dockerfile }}
          push: true
          tags: |
            optidata/optiwork-jitsi:${{ matrix.details.region }}-${{ github.ref_name }}